Spedizioni/Controllers/StatoSpedizioniController.cs
using Spedizioni.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Spedizioni.Controllers
{
    public class StatoSpedizioniController : Controller
    {

        string connectionString = ConfigurationManager.ConnectionStrings["Fedex"].ToString();

        public ActionResult ListaStatoSpedizioni()
        {
            List<AggiornamentoSpedizione> listaStatoSpedizioni = GetListaStatoSpedizioniFromDatabase();

            return View(listaStatoSpedizioni);
        }

        public ActionResult Create()
        {
            return View();
        }

        private List<AggiornamentoSpedizione> GetListaStatoSpedizioniFromDatabase()
        {
            List<AggiornamentoSpedizione> listaStatoSpedizioni = new List<AggiornamentoSpedizione>();

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                using (SqlCommand command = new SqlCommand("SELECT * FROM AggiornamentiSpedizioni", connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            AggiornamentoSpedizione Statospedizioni = new AggiornamentoSpedizione
                            {
                                AggiornamentoId = (int)reader["AggiornamentoId"],
                                SpedizioneId = (int)reader["SpedizioneId"],
                                Stato = reader["Stato"].ToString(),
                                Luogo = reader["Luogo"].ToString(),
                                Descrizione = reader["Descrizione"].ToString(),
                                DataOraAggiornamento = (DateTime)reader["DataOraAggiornamento"]

                            };

                            listaStatoSpedizioni.Add(Statospedizioni);
                        }
                    }
                }
            }

            return listaStatoSpedizioni;
        }

        [HttpPost]
        public ActionResult Create(AggiornamentoSpedizione nuovoStatoSpedizione)
        {
            if (ModelState.IsValid)
            {

                InserisciSpedizioneNelDatabase(nuovoStatoSpedizione);

                return RedirectToAction("ListaStatoSpedizioni");
            }


            return View(nuovoStatoSpedizione);
        }

        private void InserisciSpedizioneNelDatabase(AggiornamentoSpedizione nuovoStatoSpedizione)
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                string query = "INSERT INTO AggiornamentiSpedizioni (SpedizioneId, Stato, Luogo, Descrizione, DataOraAggiornamento) VALUES (@SpedizioneId, @Stato, @Luogo, @Descrizione, @DataOraAggiornamento)";

                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@SpedizioneId", nuovoStatoSpedizione.SpedizioneId);
                    command.Parameters.AddWithValue("@Stato", nuovoStatoSpedizione.Stato);
                    command.Parameters.AddWithValue("@Luogo", nuovoStatoSpedizione.Luogo);
                    command.Parameters.AddWithValue("@Descrizione", nuovoStatoSpedizione.Descrizione);
                    command.Parameters.AddWithValue("@DataOraAggiornamento", nuovoStatoSpedizione.DataOraAggiornamento);

                    command.ExecuteNonQuery();
                }
            }
        }

        public ActionResult AggiornamentiSpedizione(List<AggiornamentoSpedizione> aggiornamenti)
        {
            return View(aggiornamenti);
        }

        public ActionResult NessunaInformazioneSpedizione()
        {
            return View();
        }

        private bool VerificaAssociazioneClienteSpedizione(string codiceFiscale, string partitaIVA, int spedizioneId)
        {
            int clienteId = GetClienteIdByCodiceFiscale(codiceFiscale);

            if (clienteId > 0)
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    string query = "SELECT COUNT(*) FROM Spedizioni WHERE ClienteId = @ClienteId AND SpedizioneId = @SpedizioneId";

                    using (SqlCommand command = new SqlCommand(query, connection))
                    {
                        command.Parameters.AddWithValue("@ClienteId", clienteId);
                        command.Parameters.AddWithValue("@SpedizioneId", spedizioneId);

                        int count = (int)command.ExecuteScalar();

                        return count > 0;
                    }
                }
            }

            return false;
        }

        private bool VerificaAssociazioneClienteSpedizione1(string codiceFiscale, string partitaIVA, int spedizioneId)
        {
            int clienteId = GetClienteIdByPartitaIVA(partitaIVA);

            if (clienteId > 0)
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    string query = "SELECT COUNT(*) FROM Spedizioni WHERE ClienteId = @ClienteId AND SpedizioneId = @SpedizioneId";

                    using (SqlCommand command = new SqlCommand(query, connection))
                    {
                        command.Parameters.AddWithValue("@ClienteId", clienteId);
                        command.Parameters.AddWithValue("@SpedizioneId", spedizioneId);

                        int count = (int)command.ExecuteScalar();

                        return count > 0;
                    }
                }
            }

            return false;
        }

        private List<AggiornamentoSpedizione> GetStatiSpedizioneFromDatabase(int spedizioneId)
        {
            List<AggiornamentoSpedizione> statiSpedizione = new List<AggiornamentoSpedizione>();

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                string query = "SELECT * FROM AggiornamentiSpedizioni WHERE SpedizioneId = @SpedizioneId ORDER BY DataOraAggiornamento DESC";

                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@SpedizioneId", spedizioneId);

                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            AggiornamentoSpedizione stato = new AggiornamentoSpedizione
                            {

                                SpedizioneId = (int)reader["SpedizioneId"],
                                Stato = reader["Stato"].ToString(),
                                Luogo = reader["Luogo"].ToString(),
                                Descrizione = reader["Descrizione"].ToString(),
                                DataOraAggiornamento = (DateTime)reader["DataOraAggiornamento"]
                            };

                            statiSpedizione.Add(stato);
                        }
                    }
                }
            }

            return statiSpedizione;
        }

        public ActionResult VerificaStatoSpedizione()
        {
            return View();
        }

        [HttpPost]
        public ActionResult VerificaStatoSpedizione(VerificaStatoSpedizioni model)
        {
            switch (model.TipoCliente)
            {
                case TipoCliente.Privato:
                    if (VerificaAssociazioneClienteSpedizione(model.CodiceFiscale, null, model.SpedizioneId))
                    {
                        // Ottieni gli aggiornamenti della spedizione dal database
                        List<AggiornamentoSpedizione> aggiornamenti = GetStatiSpedizioneFromDatabase(model.SpedizioneId);
                        // Restituisci la vista con gli aggiornamenti
                        return View("AggiornamentiSpedizione", aggiornamenti);
                    }
                    break;

                case TipoCliente.Azienda:
                    if (VerificaAssociazioneClienteSpedizione1(null, model.PartitaIva, model.SpedizioneId))
                    {
                        // Ottieni gli aggiornamenti della spedizione dal database
                        List<AggiornamentoSpedizione> aggiornamenti = GetStatiSpedizioneFromDatabase(model.SpedizioneId);
                        // Restituisci la vista con gli aggiornamenti
                        return View("AggiornamentiSpedizione", aggiornamenti);
                    }
                    break;
            }

            // Se l'associazione non è confermata, restituisci una vista indicando che non sono disponibili informazioni sulla spedizione
            return View("NessunaInformazioneSpedizione");
        }


        private int GetClienteIdByCodiceFiscale(string codiceFiscale)
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                string query = "SELECT ClienteId FROM Clienti WHERE CodiceFiscale = @CodiceFiscale";

                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    // Assicurati che il parametro venga aggiunto correttamente
                    command.Parameters.Add("@CodiceFiscale", System.Data.SqlDbType.NVarChar, 16).Value = codiceFiscale;

                    // Esegui la query e restituisci il risultato
                    object result = command.ExecuteScalar();

                    if (result != null && result != DBNull.Value)
                    {

Spedizioni/Views/StatoSpedizioni/AggiornamentiSpedizione.cshtml
@model IEnumerable<Spedizioni.Models.AggiornamentoSpedizione>

@{
    ViewBag.Title = "AggiornamentiSpedizione";
}

<h2>AggiornamentiSpedizione</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AggiornamentoId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SpedizioneId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Stato)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Luogo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descrizione)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataOraAggiornamento)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AggiornamentoId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SpedizioneId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Stato)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Luogo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descrizione)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataOraAggiornamento)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

Spedizioni/Views/StatoSpedizioni/Create.cshtml
@model Spedizioni.Models.AggiornamentoSpedizione

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AggiornamentoSpedizione</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.SpedizioneId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SpedizioneId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SpedizioneId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stato, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Luogo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Luogo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Luogo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descrizione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descrizione, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descrizione, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataOraAggiornamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataOraAggiornamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataOraAggiornamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aggiorna Stato" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Torna alla Lista", "ListaStatoSpedizioni", "StatoSpedizioni", new { area = "" }, new { @class = "btn btn-primary" })
</div>

Spedizioni/Views/StatoSpedizioni/ListaStatoSpedizioni.cshtml
@model IEnumerable<Spedizioni.Models.AggiornamentoSpedizione>

@{
    ViewBag.Title = "ListaStatoSpedizioni";
}

<h2>ListaStatoSpedizioni</h2>

<p>
    @Html.ActionLink("Aggiorna Stato", "Create", "StatoSpedizioni", new { area = "" }, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AggiornamentoId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SpedizioneId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Stato)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Luogo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descrizione)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataOraAggiornamento)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AggiornamentoId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SpedizioneId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Stato)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Luogo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descrizione)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataOraAggiornamento)
        </td>
        
    </tr>
}

</table>

Spedizioni/Views/StatoSpedizioni/NessunaInformazioneSpedizione.cshtml
@{
    ViewBag.Title = "Nessuna Informazione Spedizione";
    
}

<h2>Nessuna Informazione sulla Spedizione</h2>
<p>Siamo spiacenti, ma non sono disponibili informazioni sulla spedizione inserita.</p>

Spedizioni/Views/StatoSpedizioni/VerificaStatoSpedizione.cshtml
@model Spedizioni.Models.VerificaStatoSpedizioni

@using (Html.BeginForm("VerificaStatoSpedizione", "StatoSpedizioni", FormMethod.Post))
{
    @Html.ValidationSummary(true)

    <div>
        @Html.LabelFor(model => model.TipoCliente)
        @Html.DropDownListFor(model => model.TipoCliente, new List<SelectListItem>
        {
            new SelectListItem { Text = "Privato", Value = "Privato" },
            new SelectListItem { Text = "Azienda", Value = "Azienda" }
        }, "Seleziona tipo cliente")
        @Html.ValidationMessageFor(model => model.TipoCliente)
    </div>

    <div>
        @Html.LabelFor(model => model.CodiceFiscale)
        @Html.TextBoxFor(model => model.CodiceFiscale)
        @Html.ValidationMessageFor(model => model.CodiceFiscale)
    </div>

    <div>
        @Html.LabelFor(model => model.PartitaIva)
        @Html.TextBoxFor(model => model.PartitaIva)
        @Html.ValidationMessageFor(model => model.PartitaIva)
    </div>

    <div>
        @Html.LabelFor(model => model.SpedizioneId)
        @Html.TextBoxFor(model => model.SpedizioneId)
        @Html.ValidationMessageFor(model => model.SpedizioneId)
    </div>

    <input type="submit" value="Verifica Stato Spedizione" />
}